### ISSUE TITLE
netfilter: replace skb_make_writable with skb_ensure_writable in kernel 5.3 or later

### ISSUE THREAD

**Issue by kohga** [yahoo/l3dsr#10]
Hello, 

There is an error that build fails on kernel 5.3 or later.
Specifically, the following commits have been merged in kernel 5.3-rc1.

> https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=2cf6bffc49dae26edd12af6b57c8c780590380bf

Therefore, it is necessary to replace `skb_make_writable` with `skb_ensure_writable` in `xt_DADDR.c` for kernel 5.3 or later.

**Comment by qbarnes** [comment]
This is a known issue and is already addressed in our internal release.  I'll see about updating my `hw_csum_failure` branch with the updated code maybe sometime later today.

The new code is ifdef'd for `kernel.org` and RHEL releases (including CentOS and Fedora).  I've not checked it on other distros that may cherry-pick commits out of `kernel.org`.  After I've updated the branch, you or anyone has any problems building it on a non-RHEL distro, let me know what one and what version and I'll fix it.

**Comment by qbarnes** [comment]
I made a commit to the `hw_csum_failure` branch just now that addresses your issue.  It also brings xt_DADDR.c in sync with my internal version with the exception of the default table still being `mangle`.  We need to publish `dsrtools` to this repo, which is the replacement for `yvipagent`, before we can change the default table to `raw`.

I ensured this branch will build on RHEL 6, 7, 8, Fedora, and Ubuntu 18.04.  Let me know if you find any problems.  This branch's code is still not yet fully tested in-house.  Its IPv4 & IPv6 paths for TCP and ICMP traffic are tested.  I'm still lining up internal testers for UDP.  If anyone tests this code with UDP traffic, let me know.

**Comment by kohga** [comment]
Thank you for updating the branch!!

I have confirmed that it works correctly in the following environment.
> OS: CentOS Linux release 7.7.1908 (Core)
> kernel version: 5.4.0-rc5 (mainline), 5.3.7 (stable)

We are using this l3dsr as RPM-based distros.
We usually use this with the default kernel version like `3.10.0-1062` .
However, we may use the latest kernel version for development.
In that case, I modify ksrc in `iptables-daddr.spec` and rebuild it.

**Comment by qbarnes** [comment]
Thank you for the testing!  Any chance you've tried the updated code with UDP traffic yet?

The old `iptables-daddr.spec` file you're used to using, due to dropped RHEL 4 & 5 support, has been almost completely gutted and re-written.  It's so much simpler now.  Hopefully, I'll get an update out "soon-ish".  If you'd like a sneak-peek, let me know and I'll post our internal version on a branch.  

Before, I used to sync the github version to our internal version treating internal as upstream.  With the next update, I'm flipping the direction of that arrow.  I intend to rebase our internal version to the github version, but that'll require some work to get both in sync before flipping the arrow around.

**Comment by kohga** [comment]
OK, thank you for useful information!

> Any chance you've tried the updated code with UDP traffic yet?

Sorry, we have only tested with ICMP and TCP traffic.
